# Generated by Django 2.1.3 on 2019-07-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='headline',
            field=models.CharField(default='Bon Appetit!', max_length=255),
        ),
    ]
